---
title: "analysis"
author: "Marine"
date: "12/1/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

...
## Dataset

The dataset is generated by a program that save the samples in a CSV files.

Setting the directory to the data directory.
```{r}
getwd()

setwd("/Users/Marine/Documents/1_KTH/4_Courses/3_RMSW/Script")

getwd()
```

Read in data frame.
```{r}

mdfN <- read.csv("timeN.txt",header=T,sep=';',stringsAsFactors = F)
mdfColor <- read.csv("timeColor.txt",header=T,sep=';',stringsAsFactors = F)

mdfN_ILP <- read.csv("timeN_ILP.txt",header=T,sep=';',stringsAsFactors = F)
mdfColor_ILP <- read.csv("timeColor_ILP.txt",header=T,sep=';',stringsAsFactors = F)

# check what variables are there
#names(mdfN)
#summary(mdfN)
#names(mdfColor)
#summary(mdfColor)

# conversion ns--> s
 k<-0.000000001
mdfN$time<-k*mdfN$time
mdfColor$time<-k*mdfColor$time
```



```{r}
#Plot timeN 
plot(mdfN_ILP$N, mdfN_ILP$time, main="Running time in s for 4 colors available", pch=18, col="blue")
points(mdfN$N, mdfN$time, pch=18, col="red")

#Legend
legend(x="topleft", legend=c("IPL","Our Implementation"), col=c("blue","red"), pch=c(15,15), lwd=c(0,0))

#Plot timeColor 
plot(mdfColor_ILP$color, mdfColor_ILP$time, main="Running time in s a fixed size of graph", pch=18, col="blue")
points(mdfColor$color, mdfColor$time, pch=18, col="red")
#Legend
legend(x="topright", legend=c("IPL","Our Implementation"), col=c("blue","red"), pch=c(15,15), lwd=c(0,0))

```
